### ISSUE TITLE
Can't install: possibly undefined macro: PKG_CHECK_MODULES

### ISSUE THREAD

**Issue by kristiank** [UCL-CATL/gcsvedit#13] opened 2015-12-03 13:38 UTC
Running autogen.sh I get the following error:
```
$ ./autogen.sh 
*** WARNING: I am going to run `configure' with no arguments.
*** If you wish to pass any to it, please specify them on the
*** `./autogen.sh\' command line.

autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autoreconf: running: aclocal --force --warnings=no-portability --install -I m4 ${ACLOCAL_FLAGS}
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force --warnings=no-portability
configure.ac:44: error: possibly undefined macro: PKG_CHECK_MODULES
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

But nowhere in the source code can I even find the string PKG_CHECK_MODULES.

**Comment by swilmet** [comment] 2015-12-03 13:59
Duplicate of:
https://github.com/UCL-CATL/gcsvedit/issues/11

I'll try to lower the gtk+ and gtksourceview version dependencies, at least temporarily. And write instructions on how to install gCSVedit on Linux. Or provide an xdg-app.

**Closed by swilmet** 2015-12-03 13:59 UTC
